# Generated by Django 2.1.3 on 2018-11-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='The quiz duration(in minutes)', max_digits=4),
        ),
    ]
