# Generated by Django 2.1.3 on 2018-11-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_submitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='given_mark',
            field=models.FloatField(default=0.0, help_text='Mark this assignment'),
        ),
    ]
