# Generated by Django 2.1.3 on 2018-11-10 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_submitassignment_given_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publishassignment',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='What is the last date time for this assignment submission?'),
        ),
        migrations.AddField(
            model_name='submitassignment',
            name='submission_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
